### ISSUE TITLE
Artifacts in maven public repository?

### ISSUE THREAD

**Issue by mmoayyed** [toopher/toopher-java#7]
Would it be possible to publish the build artifacts to maven's public repository?

**Comment by mmoayyed** [comment]
So it's been a full year since the initial reporting of this issue. Are we any closer to having artifacts in central?

**Comment by smholloway** [comment]
I'm not sure we're any closer, but we're no further away at least :) I plan to revisit the language library again in the first quarter of this year. 

I don't know how to publish the GA artifacts and the guides I've seen are non-trivial to follow--do you have a guide for how a Maven newbie can easily publish their artifacts?

**Comment by langedb** [comment]
http://central.sonatype.org/pages/ossrh-guide.html
